### 1. Importing Libraries

In [83]:
import pandas as pd
import numpy as np

import tensorflow as tf
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

### 2. Importing Dataset Titacnic

In [84]:
df_train = pd.read_csv('titanic/train.csv')
df_test = pd.read_csv('titanic/test.csv')

In [85]:
df_train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [86]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### 3. Data Preprocessing

In [87]:
df_train = df_train.drop(['PassengerId', 'Name', 'Ticket'], axis=1)
df_test = df_test.drop(['PassengerId', 'Name', 'Ticket'], axis=1)

In [88]:
df_train.head(10)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S
5         0       3    male   NaN      0      0   8.4583   NaN        Q
6         0       1    male  54.0      0      0  51.8625   E46        S
7         0       3    male   2.0      3      1  21.0750   NaN        S
8         1       3  female  27.0      0      2  11.1333   NaN        S
9         1       2  female  14.0      1      0  30.0708   NaN        C

In [89]:
df_test.head(10)

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0       3    male  34.5      0      0   7.8292   NaN        Q
1       3  female  47.0      1      0   7.0000   NaN        S
2       2    male  62.0      0      0   9.6875   NaN        Q
3       3    male  27.0      0      0   8.6625   NaN        S
4       3  female  22.0      1      1  12.2875   NaN        S
5       3    male  14.0      0      0   9.2250   NaN        S
6       3  female  30.0      0      0   7.6292   NaN        Q
7       2    male  26.0      1      1  29.0000   NaN        S
8       3  female  18.0      0      0   7.2292   NaN        C
9       3    male  21.0      2      0  24.1500   NaN        S

### 4. Encoding Categorical Data

In [90]:
labelencoder = LabelEncoder()

df_train['Sex'] = labelencoder.fit_transform(df_train['Sex'])
df_train['Embarked'] = labelencoder.fit_transform(df_train['Embarked'])
df_train['Cabin'] = labelencoder.fit_transform(df_train['Cabin'])
df_train['Age'] = labelencoder.fit_transform(df_train['Age'])

df_train.head(10)

Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Cabin  Embarked
0         0       3    1   28      1      0   7.2500    147         2
1         1       1    0   51      1      0  71.2833     81         0
2         1       3    0   34      0      0   7.9250    147         2
3         1       1    0   47      1      0  53.1000     55         2
4         0       3    1   47      0      0   8.0500    147         2
5         0       3    1   88      0      0   8.4583    147         1
6         0       1    1   69      0      0  51.8625    129         2
7         0       3    1    6      3      1  21.0750    147         2
8         1       3    0   35      0      2  11.1333    147         2
9         1       2    0   18      1      0  30.0708    147         0

In [91]:
df_test['Sex'] = labelencoder.fit_transform(df_test['Sex'])
df_test['Embarked'] = labelencoder.fit_transform(df_test['Embarked'])
df_test['Cabin'] = labelencoder.fit_transform(df_test['Cabin'])
df_test['Age'] = labelencoder.fit_transform(df_test['Age'])

df_test.head(10)

Pclass  Sex  Age  SibSp  Parch     Fare  Cabin  Embarked
0       3    1   44      0      0   7.8292     76         1
1       3    0   60      1      0   7.0000     76         2
2       2    1   74      0      0   9.6875     76         1
3       3    1   34      0      0   8.6625     76         2
4       3    0   27      1      1  12.2875     76         2
5       3    1   17      0      0   9.2250     76         2
6       3    0   38      0      0   7.6292     76         1
7       2    1   32      1      1  29.0000     76         2
8       3    0   22      0      0   7.2292     76         0
9       3    1   26      2      0  24.1500     76         2

### 5. Spliting Train to Train and Validation

In [92]:
X_train, X_test, y_train, y_test = train_test_split(df_train.drop(['Survived'], axis=1), df_train['Survived'], test_size=0.3, random_state=42)

X_train, X_validation, y_train, y_validation = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

### 6. Feature Scaling

In [93]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [94]:
sc.fit(X_train)

X_train = sc.transform(X_train)
X_validation = sc.transform(X_validation)

In [95]:
X_train

array([[-1.64123996, -1.42062726, -0.6637397 , ...,  0.87567151,
        -2.99216805, -2.06245978],
       [ 0.80954715, -1.42062726, -1.60311412, ..., -0.20810813,
         0.44091981,  0.54440563],
       [ 0.80954715, -1.42062726, -1.05514571, ..., -0.50794148,
         0.44091981, -0.75902708],
       ...,
       [-0.41584641,  0.70391441,  1.56727453, ..., -0.38958083,
         0.44091981,  0.54440563],
       [ 0.80954715,  0.70391441,  1.56727453, ...,  0.88128986,
         0.44091981,  0.54440563],
       [-1.64123996, -1.42062726,  0.94102492, ...,  1.18711461,
        -1.70824901, -2.06245978]])

In [96]:
X_validation

array([[ 8.09547146e-01, -1.42062726e+00, -6.63739703e-01,
         3.43285767e-01, -4.77815461e-01, -3.25531641e-01,
         4.40919813e-01,  5.44405627e-01],
       [-4.15846406e-01, -1.42062726e+00, -6.63739703e-01,
        -4.70791909e-01, -4.77815461e-01, -3.89580827e-01,
         3.01363396e-01,  5.44405627e-01],
       [ 8.09547146e-01,  7.03914409e-01,  1.97353510e-01,
         3.43285767e-01,  7.74564010e-01, -3.33397331e-01,
         4.40919813e-01, -7.59027076e-01],
       [ 8.09547146e-01,  7.03914409e-01,  1.56727453e+00,
         1.15736344e+00, -4.77815461e-01, -1.59228492e-01,
         4.40919813e-01, -7.59027076e-01],
       [-4.15846406e-01, -1.42062726e+00, -1.60311412e+00,
         3.43285767e-01,  2.02694348e+00,  2.52690925e-01,
         4.40919813e-01, -2.06245978e+00],
       [-1.64123996e+00,  7.03914409e-01,  8.23603120e-01,
        -4.70791909e-01,  7.74564010e-01,  1.05517778e+00,
        -9.26733076e-01,  5.44405627e-01],
       [-4.15846406e-01,  7.039144

In [97]:
sc.fit(X_test)

X_test = sc.transform(X_test)

X_test

array([[ 0.88612192,  0.77768272,  1.5323388 , ..., -0.38337004,
         0.48099963, -1.79208686],
       [-0.26669689,  0.77768272, -0.34030499, ..., -0.4855641 ,
         0.48099963,  0.61532807],
       [ 0.88612192,  0.77768272, -0.97780075, ..., -0.54101307,
         0.48099963,  0.61532807],
       ...,
       [-1.41951569,  0.77768272,  1.25343441, ..., -0.13995017,
        -0.09119777,  0.61532807],
       [ 0.88612192,  0.77768272, -1.0973312 , ..., -0.52513205,
         0.48099963,  0.61532807],
       [-1.41951569,  0.77768272, -0.53952241, ..., -0.13995017,
        -1.58981004,  0.61532807]])

### Training Model using Early Stopping

### Using K-Fold Cross Validation

In [98]:
bestMeanAccuracy = 0
allAccuracys = []
bestAccuracy = 0
BestOcultLayer = 0
BestsNeurons = []

ocultLayer = [1,2,3]
neuron = [16,32,64]

BATCH_SIZE = 64
EPOCHS = 100

model = tf.keras.models.Sequential()

for i in ocultLayer:

    for j in range(i):
        model.add(tf.keras.layers.Dense(neuron[j], activation='relu'))

    model.add(tf.keras.layers.Dense(3, activation='softmax'))

    model.compile(optimizer='RMSPROP', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3)

    kfold = KFold(n_splits=5, shuffle=True, random_state=42)

    meansAccuracy = []

    for train_index, validation_index in kfold.split(X_train):
        X_train_fold, X_validation_fold = X_train[train_index], X_train[validation_index]
        y_train_fold, y_validation_fold = y_train.iloc[train_index], y_train.iloc[validation_index]

        model.fit(X_train_fold, y_train_fold, epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=[early_stopping])
        _, accuracy = model.evaluate(X_validation_fold, y_validation_fold)
        meansAccuracy.append(accuracy)

    allAccuracys.append(np.mean(meansAccuracy))
    if np.mean(meansAccuracy) > bestMeanAccuracy:
        print("----------------------------------------")
        bestMeanAccuracy = np.mean(meansAccuracy)
        bestAccuracy = accuracy
        BestOcultLayer = i
        BestsNeurons = neuron[:i]

    print('Mean Accuracy: ', np.mean(meansAccuracy))

print ('Best Mean Accuracy: ', bestMeanAccuracy)
print ('Best Accuracy: ', bestAccuracy)
print ('Best Ocult Layer: ', BestOcultLayer)
print ('All Accuracys: ', allAccuracys)
print ('Bests Neurons: ', BestsNeurons)


Epoch 1/100
7/7 [==============================] - 0s 2ms/step - loss: 1.5379 - accuracy: 0.1457
Epoch 2/100
7/7 [==============================] - 0s 2ms/step - loss: 1.4269 - accuracy: 0.2286
Epoch 3/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3514 - accuracy: 0.2739
Epoch 4/100
7/7 [==============================] - 0s 2ms/step - loss: 1.2852 - accuracy: 0.3317
Epoch 5/100
7/7 [==============================] - 0s 2ms/step - loss: 1.2306 - accuracy: 0.3643
Epoch 6/100
7/7 [==============================] - 0s 2ms/step - loss: 1.1805 - accuracy: 0.4095
Epoch 7/100
7/7 [==============================] - 0s 2ms/step - loss: 1.1315 - accuracy: 0.4749
Epoch 8/100
7/7 [==============================] - 0s 2ms/step - loss: 1.0906 - accuracy: 0.5251
Epoch 9/100
7/7 [==============================] - 0s 2ms/step - loss: 1.0501 - accuracy: 0.5754
Epoch 10/100
7/7 [==============================] - 0s 2ms/step - loss: 1.0127 - accuracy: 0.6055
Epoch 11/100
7/7 [===========

### 7. Test Data set preprocessing

### 7. Testing Model using Test Dataset

In [99]:
model = tf.keras.models.Sequential()

print(BestOcultLayer)
print(BestsNeurons)

for i in range(BestOcultLayer):
    model.add(tf.keras.layers.Dense(BestsNeurons[i], activation='relu'))

model.add(tf.keras.layers.Dense(3, activation='softmax'))

model.compile(optimizer='RMSPROP', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=[early_stopping])
_, accuracy = model.evaluate(X_validation, y_validation)

print('Accuracy: ', accuracy)
print('Best Mean Accuracy: ', bestMeanAccuracy)

3
[16, 32, 64]
Epoch 1/100
8/8 [==============================] - 1s 2ms/step - loss: 0.9430 - accuracy: 0.5683
Epoch 2/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7557 - accuracy: 0.6707
Epoch 3/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6595 - accuracy: 0.7229
Epoch 4/100
8/8 [==============================] - 0s 2ms/step - loss: 0.5932 - accuracy: 0.7430
Epoch 5/100
8/8 [==============================] - 0s 2ms/step - loss: 0.5482 - accuracy: 0.7751
Epoch 6/100
8/8 [==============================] - 0s 2ms/step - loss: 0.5184 - accuracy: 0.7771
Epoch 7/100
8/8 [==============================] - 0s 2ms/step - loss: 0.4934 - accuracy: 0.7912
Epoch 8/100
8/8 [==============================] - 0s 2ms/step - loss: 0.4749 - accuracy: 0.7972
Epoch 9/100
8/8 [==============================] - 0s 2ms/step - loss: 0.4633 - accuracy: 0.8092
Epoch 10/100
8/8 [==============================] - 0s 2ms/step - loss: 0.4491 - accuracy: 0.8072
Epoch 11/100
8

In [100]:
y_pred = model.predict(X_test)

y_pred = [np.argmax(v) for v in y_pred]

9/9 [==============================] - 0s 1ms/step


### 8. More metrics

In [101]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.94      0.86       157
           1       0.88      0.66      0.75       111

    accuracy                           0.82       268
   macro avg       0.84      0.80      0.81       268
weighted avg       0.83      0.82      0.82       268



In [102]:
print(confusion_matrix(y_test, y_pred))

[[147  10]
 [ 38  73]]
