# 3 - Types and Type Conversion
Numpy supports a much wider variety of types than Python does.

There are 5 basic numeric types
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

In addition, the cell below shows a comparative table with a larger number of Numpy types.

![datatypes.png](datatypes.png)

Library importation


In [1]:
import numpy as np

Creates a var with type of float32

In [3]:
x = np.float32(1.0)
x

1.0

Creates a array with type of int

In [4]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

The arange function creates a new array filled with a sequence values starting from 0 with type of uint8

In [ ]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [7]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## Converting type of array

To convert Numpy array, just use the astype() method


Astype() function convert values to the given parameter determined type

In [ ]:
z.astype(float)

array([0., 1., 2.])

In [ ]:
np.int8(z)

array([0, 1, 2], dtype=int8)

To check the type of Numpy array, just check its dtype attibute

In [ ]:
z.dtype

dtype('uint8')